name: sqlite_viewer
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  sqflite_common_ffi: ^2.3.4
  sqlite3_flutter_libs: ^0.5.34
  file_picker: ^10.1.9
  csv: ^6.0.0
  path: ^1.9.0
  window_manager: ^0.4.3
  shared_preferences: ^2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true
